openapi: 3.0.0
info:
  title: Jobs API
  version: 1.0.0
servers:
  - url: https://jobsapi.adaptable.app/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: anna
                username: anna@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: anna@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: Google
                position: intern
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Single Job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Jobs
      summary: Update job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: netflix
                position: full stack developer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Jobs
      summary: Delete job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
